name: Build & Release

on:
  push:
    tags:
      - "v*" # Release on tags like v1.0.0
  workflow_dispatch:

permissions:
  contents: write # needed for creating releases

jobs:
  build_windows:
    name: Windows – build & pack
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: com.jonasoehler.cubase.articulation.sdPlugin

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Stream Deck CLI (optional)
        run: npm i -g @elgato/cli@latest

      - name: Build & Package (PowerShell script)
        run: powershell -NoProfile -ExecutionPolicy Bypass -File scripts/build-win.ps1

      - name: Make RemoteInstaller-win.zip
        run: |
          New-Item -ItemType Directory -Force -Path dist | Out-Null
          $zip = Join-Path "dist" "RemoteInstaller-win.zip"
          if (Test-Path $zip) { Remove-Item -Force $zip }
          $files = @(
            "remote/Elgato_StreamDeckXL.js",
            "scripts/install-remote-api.ps1",
            "scripts/install-remote-api.cmd"
          )
          Compress-Archive -Path $files -DestinationPath $zip

      - name: Upload artifact – plugin (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: plugin-windows
          path: com.jonasoehler.cubase.articulation.sdPlugin/dist/*.streamDeckPlugin
          if-no-files-found: error

      - name: Upload artifact – RemoteInstaller-win.zip
        uses: actions/upload-artifact@v4
        with:
          name: remote-installer-win
          path: com.jonasoehler.cubase.articulation.sdPlugin/dist/RemoteInstaller-win.zip
          if-no-files-found: error

  build_mac_remote:
    name: macOS – pack RemoteInstaller (exec bits)
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
        working-directory: com.jonasoehler.cubase.articulation.sdPlugin

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare exec bits
        run: |
          chmod +x scripts/install-remote-api.sh
          chmod +x scripts/install-remote-api-mac.command

      - name: Make RemoteInstaller-mac.zip
        run: |
          mkdir -p dist
          cd scripts
          zip -r ../dist/RemoteInstaller-mac.zip \
            "../remote/Elgato_StreamDeckXL.js" \
            "install-remote-api.sh" \
            "install-remote-api-mac.command"

      - name: Upload artifact – RemoteInstaller-mac.zip
        uses: actions/upload-artifact@v4
        with:
          name: remote-installer-mac
          path: com.jonasoehler.cubase.articulation.sdPlugin/dist/RemoteInstaller-mac.zip
          if-no-files-found: error

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build_windows, build_mac_remote]

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist-collect

      - name: List collected artifacts
        run: ls -R dist-collect

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist-collect/plugin-windows/*.streamDeckPlugin
            dist-collect/remote-installer-win/RemoteInstaller-win.zip
            dist-collect/remote-installer-mac/RemoteInstaller-mac.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
